# Generated by Django 2.0.9 on 2018-11-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181125_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('not-specified', 'Not specified'), ('female', 'Female'), ('male', 'Male')], max_length=80, null=True),
        ),
    ]
